/**
 * RAM SCORING CONFIGURATION
 *
 * The calculators use fixed anchors rather than dataset min/max values. The
 * legacy property names remain available to the product-metrics panel.
 */
export const RAM_CONFIG = {
  VELOCIDAD: {
    BANDWIDTH_BASELINE_GBPS: 20,
    BANDWIDTH_ANCHOR_GBPS: 100,
    FRECUENCIA: { POINTS: 5000, MAX_MHZ: 8400 },
    ANCHO_BANDA: { POINTS: 5000, MAX_GBPS: 100 },
    TOTAL_POINTS: 10000,
  },
  TECNOLOGIAS: {
    GENERACION_WEIGHT: 0.4,
    PERFILES_WEIGHT: 0.3,
    ELECTRONICA_WEIGHT: 0.15,
    OVERCLOCKING_WEIGHT: 0.1,
    COMPATIBILIDAD_WEIGHT: 0.05,
    PLATAFORMA_WEIGHT: 0.95,
    TOTAL_POINTS: 10000,
  },
  LATENCIA: {
    BEST_NS: 8,
    WORST_NS: 16,
    REAL: { POINTS: 6000, MAX_NS: 8, MIN_NS: 16 },
    TEORICA: { POINTS: 4000, MAX_NS: 8, MIN_NS: 16 },
    TOTAL_POINTS: 10000,
  },
  JUEGOS: {
    SPEED_WEIGHT: 0.45,
    LATENCY_WEIGHT: 0.35,
    CHANNEL_WEIGHT: 0.15,
    STABILITY_WEIGHT: 0.05,
    CAPACITY_FLOOR_GB: 16,
    TOTAL_POINTS: 10000,
  },
  PRODUCTIVIDAD: {
    CAPACITY_WEIGHT: 0.45,
    SPEED_WEIGHT: 0.3,
    CHANNEL_WEIGHT: 0.15,
    LATENCY_WEIGHT: 0.1,
    TOTAL_POINTS: 10000,
  },
  VALUE_WEIGHTS: {
    VELOCIDAD_WEIGHT: 30,
    PRODUCTIVIDAD_WEIGHT: 25,
    LATENCIA_WEIGHT: 20,
    TECNOLOGIAS_WEIGHT: 15,
    JUEGOS_WEIGHT: 10,
  },
  VALUE_PRICE_REFERENCE: 100,
  VALUE_PRICE_EXPONENT: 0.65,
};
