SET local check_function_bodies = off;

CREATE TABLE "public"."ai_action_logs" (
  "id"                   uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "created_at"           timestamp with time zone NOT NULL DEFAULT now(),
  "user_id"              uuid                     NOT NULL,
  "is_anonymous"         boolean                  NOT NULL,
  "ip_hash"              text,
  "provider"             text                     NOT NULL,
  "model"                text                     NOT NULL,
  "duration_ms"          integer                  NOT NULL DEFAULT 0,
  "input_tokens"         integer                  NOT NULL DEFAULT 0,
  "output_tokens"        integer                  NOT NULL DEFAULT 0,
  "tool_calls"           integer                  NOT NULL DEFAULT 0,
  "status"               text                     NOT NULL,
  "error_code"           text,
  "failure_stage"        text,
  "provider_http_status" smallint,
  "finish_reason"        text,
  CONSTRAINT "ai_action_logs_duration_ms_check" CHECK ((duration_ms >= 0)),
  CONSTRAINT "ai_action_logs_input_tokens_check" CHECK ((input_tokens >= 0)),
  CONSTRAINT "ai_action_logs_output_tokens_check" CHECK ((output_tokens >= 0)),
  CONSTRAINT "ai_action_logs_pkey" PRIMARY KEY (id),
  CONSTRAINT "ai_action_logs_provider_check" CHECK ((provider = ANY (ARRAY['local'::text, 'groq'::text, 'cerebras'::text, 'openrouter'::text, 'guardrail'::text]))),
  CONSTRAINT "ai_action_logs_status_check" CHECK ((status = ANY (ARRAY['success'::text, 'error'::text, 'guardrail'::text, 'rate_limited'::text]))),
  CONSTRAINT "ai_action_logs_tool_calls_check" CHECK ((tool_calls >= 0))
);

ALTER TABLE "public"."ai_action_logs"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."ai_conversation_messages" (
  "id"              bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "conversation_id" uuid                     NOT NULL,
  "role"            text                     NOT NULL,
  "content"         text                     NOT NULL,
  "metadata"        jsonb                    NOT NULL DEFAULT '{}'::jsonb,
  "created_at"      timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "ai_conversation_messages_content_check" CHECK (((char_length(content) >= 1) AND (char_length(content) <= 12000))),
  CONSTRAINT "ai_conversation_messages_pkey" PRIMARY KEY (id),
  CONSTRAINT "ai_conversation_messages_role_check" CHECK ((role = ANY (ARRAY['user'::text, 'assistant'::text])))
);

ALTER TABLE "public"."ai_conversation_messages"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."ai_conversations" (
  "id"              uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "user_id"         uuid                     NOT NULL,
  "title"           text                     NOT NULL,
  "state"           jsonb                    NOT NULL DEFAULT '{}'::jsonb,
  "message_count"   integer                  NOT NULL DEFAULT 0,
  "created_at"      timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"      timestamp with time zone NOT NULL DEFAULT now(),
  "last_message_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "ai_conversations_message_count_check" CHECK ((message_count >= 0)),
  CONSTRAINT "ai_conversations_pkey" PRIMARY KEY (id),
  CONSTRAINT "ai_conversations_title_check" CHECK (((char_length(title) >= 1) AND (char_length(title) <= 80)))
);

ALTER TABLE "public"."ai_conversations"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."ai_pending_actions" (
  "id"             uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "user_id"        uuid                     NOT NULL,
  "action_type"    text                     NOT NULL,
  "payload"        jsonb                    NOT NULL,
  "payload_digest" text                     NOT NULL,
  "created_at"     timestamp with time zone NOT NULL DEFAULT now(),
  "expires_at"     timestamp with time zone NOT NULL,
  "consumed_at"    timestamp with time zone,
  CONSTRAINT "ai_pending_actions_action_type_check" CHECK ((action_type = ANY (ARRAY['create_combo'::text, 'create_build'::text, 'set_custom_price'::text]))),
  CONSTRAINT "ai_pending_actions_check" CHECK ((expires_at > created_at)),
  CONSTRAINT "ai_pending_actions_payload_digest_check" CHECK ((payload_digest ~ '^[a-f0-9]{64}$'::text)),
  CONSTRAINT "ai_pending_actions_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."ai_pending_actions"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."ai_quota_config" (
  "singleton"                           boolean                  NOT NULL DEFAULT true,
  "anonymous_daily_messages"            integer                  NOT NULL DEFAULT 20,
  "authenticated_daily_messages"        integer                  NOT NULL DEFAULT 200,
  "anonymous_daily_tokens"              bigint                   NOT NULL DEFAULT 30000,
  "authenticated_daily_tokens"          bigint                   NOT NULL DEFAULT 200000,
  "anonymous_ip_daily_messages"         integer                  NOT NULL DEFAULT 60,
  "authenticated_ip_daily_messages"     integer                  NOT NULL DEFAULT 500,
  "anonymous_ip_daily_tokens"           bigint                   NOT NULL DEFAULT 90000,
  "authenticated_ip_daily_tokens"       bigint                   NOT NULL DEFAULT 500000,
  "updated_at"                          timestamp with time zone NOT NULL DEFAULT now(),
  "anonymous_daily_web_searches"        integer                  NOT NULL DEFAULT 3,
  "authenticated_daily_web_searches"    integer                  NOT NULL DEFAULT 10,
  "anonymous_ip_daily_web_searches"     integer                  NOT NULL DEFAULT 6,
  "authenticated_ip_daily_web_searches" integer                  NOT NULL DEFAULT 20,
  CONSTRAINT "ai_quota_config_anonymous_daily_messages_check" CHECK ((anonymous_daily_messages > 0)),
  CONSTRAINT "ai_quota_config_anonymous_daily_tokens_check" CHECK ((anonymous_daily_tokens > 0)),
  CONSTRAINT "ai_quota_config_anonymous_daily_web_searches_check" CHECK ((anonymous_daily_web_searches > 0)),
  CONSTRAINT "ai_quota_config_anonymous_ip_daily_messages_check" CHECK ((anonymous_ip_daily_messages > 0)),
  CONSTRAINT "ai_quota_config_anonymous_ip_daily_tokens_check" CHECK ((anonymous_ip_daily_tokens > 0)),
  CONSTRAINT "ai_quota_config_anonymous_ip_daily_web_searches_check" CHECK ((anonymous_ip_daily_web_searches > 0)),
  CONSTRAINT "ai_quota_config_authenticated_daily_messages_check" CHECK ((authenticated_daily_messages > 0)),
  CONSTRAINT "ai_quota_config_authenticated_daily_tokens_check" CHECK ((authenticated_daily_tokens > 0)),
  CONSTRAINT "ai_quota_config_authenticated_daily_web_searches_check" CHECK ((authenticated_daily_web_searches > 0)),
  CONSTRAINT "ai_quota_config_authenticated_ip_daily_messages_check" CHECK ((authenticated_ip_daily_messages > 0)),
  CONSTRAINT "ai_quota_config_authenticated_ip_daily_tokens_check" CHECK ((authenticated_ip_daily_tokens > 0)),
  CONSTRAINT "ai_quota_config_authenticated_ip_daily_web_searches_check" CHECK ((authenticated_ip_daily_web_searches > 0)),
  CONSTRAINT "ai_quota_config_pkey" PRIMARY KEY (singleton),
  CONSTRAINT "ai_quota_config_singleton_check" CHECK ((singleton IS TRUE))
);

ALTER TABLE "public"."ai_quota_config"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."ai_usage_daily" (
  "usage_date"        date                     NOT NULL,
  "bucket_scope"      text                     NOT NULL,
  "bucket_key"        text                     NOT NULL,
  "user_id"           uuid,
  "ip_hash"           text,
  "is_anonymous"      boolean                  NOT NULL,
  "messages_used"     integer                  NOT NULL DEFAULT 0,
  "reserved_tokens"   bigint                   NOT NULL DEFAULT 0,
  "last_used_at"      timestamp with time zone NOT NULL DEFAULT now(),
  "web_searches_used" integer                  NOT NULL DEFAULT 0,
  CONSTRAINT "ai_usage_daily_bucket_scope_check" CHECK ((bucket_scope = ANY (ARRAY['user'::text, 'ip'::text]))),
  CONSTRAINT "ai_usage_daily_check" CHECK ((((bucket_scope = 'user'::text) AND (user_id IS
    NOT NULL) AND (ip_hash IS NULL)) OR ((bucket_scope = 'ip'::text) AND (user_id IS NULL) AND (ip_hash IS NOT NULL)))),
  CONSTRAINT "ai_usage_daily_messages_used_check" CHECK ((messages_used >= 0)),
  CONSTRAINT "ai_usage_daily_pkey" PRIMARY KEY (usage_date, bucket_scope, bucket_key),
  CONSTRAINT "ai_usage_daily_reserved_tokens_check" CHECK ((reserved_tokens >= 0)),
  CONSTRAINT "ai_usage_daily_web_searches_used_check" CHECK ((web_searches_used >= 0))
);

ALTER TABLE "public"."ai_usage_daily"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."builds" (
  "id"                           uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "title"                        text                     NOT NULL,
  "slug"                         text                     NOT NULL,
  "category"                     text                     NOT NULL DEFAULT 'Gaming'::text,
  "is_active"                    boolean                  NOT NULL DEFAULT true,
  "cpu_id"                       text                     NOT NULL,
  "gpu_id"                       text                     NOT NULL,
  "ram_id"                       text                     NOT NULL,
  "motherboard_id"               text                     NOT NULL,
  "storage_id"                   text                     NOT NULL,
  "psu_id"                       text                     NOT NULL,
  "created_at"                   timestamp with time zone NOT NULL DEFAULT now(),
  "custom_price_cpu_usd"         numeric(12,2),
  "custom_price_cpu_eur"         numeric(12,2),
  "custom_price_gpu_usd"         numeric(12,2),
  "custom_price_gpu_eur"         numeric(12,2),
  "custom_price_ram_usd"         numeric(12,2),
  "custom_price_ram_eur"         numeric(12,2),
  "custom_price_motherboard_usd" numeric(12,2),
  "custom_price_motherboard_eur" numeric(12,2),
  "custom_price_storage_usd"     numeric(12,2),
  "custom_price_storage_eur"     numeric(12,2),
  "custom_price_psu_usd"         numeric(12,2),
  "custom_price_psu_eur"         numeric(12,2),
  "sort_order"                   integer                  NOT NULL DEFAULT 0,
  CONSTRAINT "builds_pkey" PRIMARY KEY (id),
  CONSTRAINT "builds_slug_key" UNIQUE (slug)
);

ALTER TABLE "public"."builds"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."catalog_category_orders" (
  "catalog_kind" text    NOT NULL,
  "category"     text    NOT NULL,
  "sort_order"   integer NOT NULL,
  CONSTRAINT "catalog_category_orders_catalog_kind_check" CHECK ((catalog_kind = ANY (ARRAY['builds'::text, 'combos'::text]))),
  CONSTRAINT "catalog_category_orders_catalog_kind_sort_order_key" UNIQUE (catalog_kind, sort_order),
  CONSTRAINT "catalog_category_orders_category_check" CHECK ((length(TRIM(BOTH FROM category)) > 0)),
  CONSTRAINT "catalog_category_orders_pkey" PRIMARY KEY (catalog_kind, category)
);

ALTER TABLE "public"."catalog_category_orders"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."combos" (
  "id"                   uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "title"                text                     NOT NULL,
  "category"             text                     NOT NULL,
  "is_active"            boolean                  DEFAULT true,
  "cpu_id"               text,
  "gpu_id"               text,
  "ram_id"               text,
  "custom_price_cpu_usd" numeric(10,2),
  "custom_price_cpu_eur" numeric(10,2),
  "custom_price_gpu_usd" numeric(10,2),
  "custom_price_gpu_eur" numeric(10,2),
  "custom_price_ram_usd" numeric(10,2),
  "custom_price_ram_eur" numeric(10,2),
  "created_at"           timestamp with time zone DEFAULT now(),
  "slug"                 text,
  "sort_order"           integer                  NOT NULL DEFAULT 0,
  CONSTRAINT "combos_pkey" PRIMARY KEY (id),
  CONSTRAINT "combos_slug_key" UNIQUE (slug)
);

ALTER TABLE "public"."combos"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."created_builds" (
  "id"                           uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "user_id"                      uuid                     NOT NULL,
  "title"                        text                     NOT NULL,
  "slug"                         text                     NOT NULL,
  "category"                     text                     NOT NULL DEFAULT 'Personalizada'::text,
  "is_active"                    boolean                  NOT NULL DEFAULT true,
  "cpu_id"                       text                     NOT NULL,
  "gpu_id"                       text                     NOT NULL,
  "ram_id"                       text                     NOT NULL,
  "motherboard_id"               text                     NOT NULL,
  "storage_id"                   text                     NOT NULL,
  "psu_id"                       text                     NOT NULL,
  "custom_price_cpu_usd"         numeric,
  "custom_price_cpu_eur"         numeric,
  "custom_price_gpu_usd"         numeric,
  "custom_price_gpu_eur"         numeric,
  "custom_price_ram_usd"         numeric,
  "custom_price_ram_eur"         numeric,
  "custom_price_motherboard_usd" numeric,
  "custom_price_motherboard_eur" numeric,
  "custom_price_storage_usd"     numeric,
  "custom_price_storage_eur"     numeric,
  "custom_price_psu_usd"         numeric,
  "custom_price_psu_eur"         numeric,
  "created_at"                   timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "created_builds_pkey" PRIMARY KEY (id),
  CONSTRAINT "created_builds_user_slug_key" UNIQUE (user_id, slug)
);

ALTER TABLE "public"."created_builds"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."created_combos" (
  "id"                   uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "user_id"              uuid                     NOT NULL,
  "title"                text                     NOT NULL,
  "slug"                 text                     NOT NULL,
  "cpu_id"               text                     NOT NULL,
  "gpu_id"               text                     NOT NULL,
  "ram_id"               text                     NOT NULL,
  "custom_price_cpu_usd" numeric,
  "custom_price_cpu_eur" numeric,
  "custom_price_gpu_usd" numeric,
  "custom_price_gpu_eur" numeric,
  "custom_price_ram_usd" numeric,
  "custom_price_ram_eur" numeric,
  "created_at"           timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "created_combos_pkey" PRIMARY KEY (id),
  CONSTRAINT "created_combos_slug_key" UNIQUE (slug)
);

ALTER TABLE "public"."created_combos"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."games" (
  "id"               uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "slug"             character varying(255)   NOT NULL,
  "name"             character varying(255)   NOT NULL,
  "limite_motor_fps" integer                  NOT NULL,
  "cpu_score_ideal"  integer                  NOT NULL,
  "ram_minima_gb"    integer                  NOT NULL,
  "vram_minima_gb"   integer                  NOT NULL,
  "gpu_fps_base"     jsonb                    NOT NULL DEFAULT '{}'::jsonb,
  "created_at"       timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT "games_pkey" PRIMARY KEY (id),
  CONSTRAINT "games_slug_key" UNIQUE (slug)
);

CREATE TABLE "public"."home_comparison_items" (
  "id"            uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "comparison_id" uuid                     NOT NULL,
  "product_id"    text,
  "combo_id"      uuid,
  "build_id"      uuid,
  "sort_order"    integer                  NOT NULL DEFAULT 0,
  "created_at"    timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "home_comparison_items_check" CHECK ((num_nonnulls(product_id, combo_id, build_id) = 1)),
  CONSTRAINT "home_comparison_items_comparison_id_build_id_key" UNIQUE (comparison_id, build_id),
  CONSTRAINT "home_comparison_items_comparison_id_combo_id_key" UNIQUE (comparison_id, combo_id),
  CONSTRAINT "home_comparison_items_comparison_id_product_id_key" UNIQUE (comparison_id, product_id),
  CONSTRAINT "home_comparison_items_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."home_comparison_items"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."home_comparisons" (
  "id"          uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "section_id"  uuid                     NOT NULL,
  "title"       text                     NOT NULL,
  "description" text                     NOT NULL DEFAULT ''::text,
  "eyebrow"     text                     NOT NULL DEFAULT ''::text,
  "item_type"   text                     NOT NULL,
  "is_active"   boolean                  NOT NULL DEFAULT true,
  "sort_order"  integer                  NOT NULL DEFAULT 0,
  "created_at"  timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"  timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "home_comparisons_description_check" CHECK ((length(description) <= 360)),
  CONSTRAINT "home_comparisons_eyebrow_check" CHECK ((length(eyebrow) <= 80)),
  CONSTRAINT "home_comparisons_item_type_check" CHECK ((item_type = ANY (ARRAY['products'::text, 'combos'::text, 'builds'::text]))),
  CONSTRAINT "home_comparisons_pkey" PRIMARY KEY (id),
  CONSTRAINT "home_comparisons_title_check" CHECK (((length(TRIM(BOTH FROM title)) >= 1) AND (length(TRIM(BOTH FROM title)) <= 120)))
);

ALTER TABLE "public"."home_comparisons"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."home_hero" (
  "id"              boolean                  NOT NULL DEFAULT true,
  "eyebrow"         text                     NOT NULL DEFAULT 'CoreXScoring'::text,
  "title"           text                     NOT NULL DEFAULT 'Decide tu próximo equipo con datos.'::text,
  "description"     text                     NOT NULL DEFAULT 'Compara hardware, descubre configuraciones equilibradas y encuentra la mejor opción para tu presupuesto.'::text,
  "primary_label"   text                     NOT NULL DEFAULT 'Explorar catálogo'::text,
  "primary_href"    text                     NOT NULL DEFAULT '/catalog'::text,
  "secondary_label" text                     NOT NULL DEFAULT 'Abrir comparador'::text,
  "secondary_href"  text                     NOT NULL DEFAULT '/comparator'::text,
  "is_active"       boolean                  NOT NULL DEFAULT true,
  "updated_at"      timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "home_hero_id_check" CHECK ((id = true)),
  CONSTRAINT "home_hero_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."home_hero"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."home_section_items" (
  "id"         uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "section_id" uuid                     NOT NULL,
  "product_id" text,
  "combo_id"   uuid,
  "build_id"   uuid,
  "sort_order" integer                  NOT NULL DEFAULT 0,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "home_section_items_check" CHECK ((num_nonnulls(product_id, combo_id, build_id) = 1)),
  CONSTRAINT "home_section_items_pkey" PRIMARY KEY (id),
  CONSTRAINT "home_section_items_section_id_build_id_key" UNIQUE (section_id, build_id),
  CONSTRAINT "home_section_items_section_id_combo_id_key" UNIQUE (section_id, combo_id),
  CONSTRAINT "home_section_items_section_id_product_id_key" UNIQUE (section_id, product_id)
);

ALTER TABLE "public"."home_section_items"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."home_sections" (
  "id"             uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "title"          text                     NOT NULL,
  "description"    text                     NOT NULL DEFAULT ''::text,
  "eyebrow"        text                     NOT NULL DEFAULT ''::text,
  "content_type"   text                     NOT NULL,
  "visual_variant" text                     NOT NULL DEFAULT 'default'::text,
  "is_active"      boolean                  NOT NULL DEFAULT true,
  "sort_order"     integer                  NOT NULL DEFAULT 0,
  "created_at"     timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"     timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "home_sections_content_type_check" CHECK ((content_type = ANY (ARRAY['products'::text, 'combos'::text, 'builds'::text, 'comparisons'::text]))),
  CONSTRAINT "home_sections_description_check" CHECK ((length(description) <= 360)),
  CONSTRAINT "home_sections_eyebrow_check" CHECK ((length(eyebrow) <= 80)),
  CONSTRAINT "home_sections_pkey" PRIMARY KEY (id),
  CONSTRAINT "home_sections_title_check" CHECK (((length(TRIM(BOTH FROM title)) >= 1) AND (length(TRIM(BOTH FROM title)) <= 120))),
  CONSTRAINT "home_sections_visual_variant_check" CHECK ((visual_variant = ANY (ARRAY['default'::text, 'spotlight'::text, 'compact'::text])))
);

ALTER TABLE "public"."home_sections"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."products_gpu_compatibility_backup_20260813" (
  "id"             text,
  "slug"           text,
  "market_segment" text,
  "name"           text,
  "brand"          text,
  "type"           text,
  "category"       text,
  "description"    text,
  "price_base_usd" numeric,
  "release_date"   date,
  "release_year"   integer,
  "compatibility"  jsonb,
  "specs"          jsonb,
  "technologies"   jsonb,
  "benchmarks"     jsonb,
  "tags"           jsonb,
  "created_at"     timestamp with time zone,
  "price_base_eur" numeric
);

ALTER TABLE "public"."products_gpu_compatibility_backup_20260813"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."products" (
  "id"             text                     NOT NULL,
  "slug"           text                     NOT NULL,
  "market_segment" text,
  "name"           text                     NOT NULL,
  "brand"          text                     NOT NULL,
  "type"           text                     NOT NULL,
  "category"       text,
  "description"    text,
  "price_base_usd" numeric,
  "release_date"   date,
  "release_year"   integer,
  "compatibility"  jsonb                    DEFAULT '{}'::jsonb,
  "specs"          jsonb                    DEFAULT '{}'::jsonb,
  "technologies"   jsonb                    DEFAULT '[]'::jsonb,
  "benchmarks"     jsonb                    DEFAULT '{}'::jsonb,
  "tags"           jsonb                    DEFAULT '[]'::jsonb,
  "created_at"     timestamp with time zone DEFAULT now(),
  "price_base_eur" numeric,
  "price_eur"      numeric,
  "price_usd"      numeric,
  CONSTRAINT "products_pkey" PRIMARY KEY (id),
  CONSTRAINT "products_slug_key" UNIQUE (slug)
);

ALTER TABLE "public"."products"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."saved_builds" (
  "id"         uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "user_id"    uuid                     NOT NULL,
  "build_id"   uuid                     NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "saved_builds_pkey" PRIMARY KEY (id),
  CONSTRAINT "saved_builds_user_id_build_id_key" UNIQUE (user_id, build_id)
);

ALTER TABLE "public"."saved_builds"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."saved_combos" (
  "user_id"    uuid                     NOT NULL,
  "combo_id"   uuid                     NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "saved_combos_pkey" PRIMARY KEY (user_id, combo_id)
);

ALTER TABLE "public"."saved_combos"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."saved_products" (
  "user_id"    uuid                     NOT NULL,
  "product_id" text                     NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "saved_products_pkey" PRIMARY KEY (user_id, product_id)
);

ALTER TABLE "public"."saved_products"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."user_ai_chat_settings" (
  "user_id"                       uuid                     NOT NULL,
  "credential_mode"               text                     NOT NULL DEFAULT 'project'::text,
  "preferred_provider"            text                     NOT NULL DEFAULT 'openrouter'::text,
  "preferred_model"               text                     NOT NULL DEFAULT ''::text,
  "groq_api_key_ciphertext"       text,
  "groq_key_hint"                 text,
  "openrouter_api_key_ciphertext" text,
  "openrouter_key_hint"           text,
  "created_at"                    timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"                    timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "user_ai_chat_settings_credential_mode_check" CHECK ((credential_mode = ANY (ARRAY['project'::text, 'byok'::text]))),
  CONSTRAINT "user_ai_chat_settings_pkey" PRIMARY KEY (user_id),
  CONSTRAINT "user_ai_chat_settings_preferred_provider_check" CHECK ((preferred_provider = ANY (ARRAY['groq'::text, 'openrouter'::text])))
);

ALTER TABLE "public"."user_ai_chat_settings"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."user_ai_web_search_settings" (
  "user_id"                   uuid                     NOT NULL,
  "preferred_provider"        text                     NOT NULL DEFAULT 'tavily'::text,
  "tavily_api_key_ciphertext" text,
  "tavily_key_hint"           text,
  "brave_api_key_ciphertext"  text,
  "brave_key_hint"            text,
  "created_at"                timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"                timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "user_ai_web_search_settings_pkey" PRIMARY KEY (user_id),
  CONSTRAINT "user_ai_web_search_settings_preferred_provider_check" CHECK ((preferred_provider = ANY (ARRAY['tavily'::text, 'brave'::text])))
);

ALTER TABLE "public"."user_ai_web_search_settings"
  ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.append_ai_conversation_turn (
  p_user_id           uuid,
  p_conversation_id   uuid,
  p_user_content      text,
  p_assistant_content text,
  p_metadata          jsonb DEFAULT '{}'::jsonb,
  p_state             jsonb DEFAULT '{}'::jsonb,
  p_title             text  DEFAULT NULL::text
)
  RETURNS uuid
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
declare
  v_conversation_id uuid := p_conversation_id;
  v_title text := left(regexp_replace(coalesce(trim(p_title), ''), '\s+', ' ', 'g'), 80);
begin
  if p_user_id is null or char_length(trim(coalesce(p_user_content, ''))) = 0
    or char_length(trim(coalesce(p_assistant_content, ''))) = 0 then
    raise exception 'ai_conversation_turn_invalid' using errcode = '22023';
  end if;

  if v_conversation_id is null then
    if v_title = '' then v_title := left(trim(p_user_content), 80); end if;
    v_conversation_id := public.create_ai_conversation(p_user_id, v_title);
  end if;

  if not exists (
    select 1 from public.ai_conversations
    where id = v_conversation_id and user_id = p_user_id
  ) then
    raise exception 'ai_conversation_not_owned' using errcode = '42501';
  end if;

  insert into public.ai_conversation_messages (conversation_id, role, content, metadata)
  values
    (v_conversation_id, 'user', left(trim(p_user_content), 12000), '{}'::jsonb),
    (v_conversation_id, 'assistant', left(trim(p_assistant_content), 12000), coalesce(p_metadata, '{}'::jsonb));

  update public.ai_conversations
  set state = coalesce(p_state, '{}'::jsonb),
      message_count = (select count(*) from public.ai_conversation_messages where conversation_id = v_conversation_id),
      updated_at = now(),
      last_message_at = now()
  where id = v_conversation_id and user_id = p_user_id;

  -- Mantiene el tamaño de cada conversación acotado sin afectar el límite de
  -- conversaciones guardadas. La UI puede informar esta retención.
  delete from public.ai_conversation_messages
  where conversation_id = v_conversation_id
    and id not in (
      select id from public.ai_conversation_messages
      where conversation_id = v_conversation_id
      order by id desc
      limit 150
    );

  update public.ai_conversations
  set message_count = (select count(*) from public.ai_conversation_messages where conversation_id = v_conversation_id)
  where id = v_conversation_id and user_id = p_user_id;

  return v_conversation_id;
end;
$function$;

CREATE OR REPLACE FUNCTION public.cleanup_ai_telemetry (
  p_retention_days integer DEFAULT 90
)
  RETURNS jsonb
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
declare
  v_retention_days integer := greatest(30, least(coalesce(p_retention_days, 90), 730));
  v_deleted_logs bigint;
  v_deleted_usage bigint;
begin
  if auth.uid() is null
    or (auth.jwt() -> 'app_metadata' ->> 'role') is distinct from 'admin' then
    raise exception 'AI telemetry cleanup access denied' using errcode = '42501';
  end if;

  delete from public.ai_action_logs
  where created_at < now() - make_interval(days => v_retention_days);
  get diagnostics v_deleted_logs = row_count;

  delete from public.ai_usage_daily
  where usage_date < timezone('utc', now())::date - v_retention_days;
  get diagnostics v_deleted_usage = row_count;

  return jsonb_build_object(
    'retention_days', v_retention_days,
    'deleted_action_logs', v_deleted_logs,
    'deleted_usage_daily', v_deleted_usage
  );
end;
$function$;

CREATE OR REPLACE FUNCTION public.consume_ai_pending_action (
  p_action_id      uuid,
  p_payload_digest text
)
  RETURNS jsonb
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
declare
  v_action public.ai_pending_actions%rowtype;
begin
  if auth.uid() is null
    or coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) then
    raise exception 'AI pending action requires a permanent account' using errcode = '42501';
  end if;

  select * into v_action
  from public.ai_pending_actions
  where id = p_action_id
    and user_id = auth.uid()
    and consumed_at is null
    and expires_at > now()
    and payload_digest = lower(p_payload_digest)
  for update;

  if not found then
    raise exception 'AI pending action is expired, consumed or inaccessible' using errcode = 'P0002';
  end if;

  update public.ai_pending_actions
  set consumed_at = now()
  where id = v_action.id;

  return jsonb_build_object(
    'action_type', v_action.action_type,
    'payload', v_action.payload
  );
end;
$function$;

CREATE OR REPLACE FUNCTION public.consume_ai_quota (
  p_user_id         uuid,
  p_ip_hash         text,
  p_is_anonymous    boolean,
  p_reserved_tokens integer
)
  RETURNS jsonb
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
declare
  v_config public.ai_quota_config%rowtype;
  v_user_messages integer;
  v_user_tokens bigint;
  v_ip_messages integer;
  v_ip_tokens bigint;
  v_user_message_limit integer;
  v_user_token_limit bigint;
  v_ip_message_limit integer;
  v_ip_token_limit bigint;
  v_retry_after integer;
  v_is_anonymous boolean := coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false);
begin
  if auth.uid() is null or auth.uid() is distinct from p_user_id then
    raise exception 'AI quota user mismatch' using errcode = '42501';
  end if;

  if p_is_anonymous is distinct from v_is_anonymous then
    raise exception 'AI quota actor mismatch' using errcode = '42501';
  end if;

  if p_reserved_tokens < 0 or p_reserved_tokens > 20000 then
    raise exception 'AI quota token reservation is invalid' using errcode = '22023';
  end if;

  select * into v_config from public.ai_quota_config where singleton is true;
  if not found then raise exception 'AI quota configuration is missing' using errcode = 'P0001'; end if;

  v_user_message_limit := case when v_is_anonymous then v_config.anonymous_daily_messages else v_config.authenticated_daily_messages end;
  v_user_token_limit := case when v_is_anonymous then v_config.anonymous_daily_tokens else v_config.authenticated_daily_tokens end;
  v_ip_message_limit := case when v_is_anonymous then v_config.anonymous_ip_daily_messages else v_config.authenticated_ip_daily_messages end;
  v_ip_token_limit := case when v_is_anonymous then v_config.anonymous_ip_daily_tokens else v_config.authenticated_ip_daily_tokens end;
  v_retry_after := greatest(1, extract(epoch from (date_trunc('day', timezone('utc', now())) + interval '1 day' - timezone('utc', now())))::integer);

  insert into public.ai_usage_daily (usage_date, bucket_scope, bucket_key, user_id, is_anonymous)
  values (timezone('utc', now())::date, 'user', p_user_id::text, p_user_id, v_is_anonymous)
  on conflict (usage_date, bucket_scope, bucket_key) do nothing;

  select messages_used, reserved_tokens into v_user_messages, v_user_tokens
  from public.ai_usage_daily
  where usage_date = timezone('utc', now())::date and bucket_scope = 'user' and bucket_key = p_user_id::text
  for update;

  if p_ip_hash is not null then
    insert into public.ai_usage_daily (usage_date, bucket_scope, bucket_key, ip_hash, is_anonymous)
    values (timezone('utc', now())::date, 'ip', p_ip_hash, p_ip_hash, v_is_anonymous)
    on conflict (usage_date, bucket_scope, bucket_key) do nothing;
    select messages_used, reserved_tokens into v_ip_messages, v_ip_tokens
    from public.ai_usage_daily
    where usage_date = timezone('utc', now())::date and bucket_scope = 'ip' and bucket_key = p_ip_hash
    for update;
  end if;

  if v_user_messages + 1 > v_user_message_limit then
    return jsonb_build_object('allowed', false, 'reason', 'user_messages', 'retry_after_seconds', v_retry_after, 'user_remaining_messages', greatest(0, v_user_message_limit - v_user_messages));
  end if;
  if v_user_tokens + p_reserved_tokens > v_user_token_limit then
    return jsonb_build_object('allowed', false, 'reason', 'user_tokens', 'retry_after_seconds', v_retry_after, 'user_remaining_messages', greatest(0, v_user_message_limit - v_user_messages));
  end if;
  if p_ip_hash is not null and v_ip_messages + 1 > v_ip_message_limit then
    return jsonb_build_object('allowed', false, 'reason', 'ip_messages', 'retry_after_seconds', v_retry_after, 'ip_remaining_messages', greatest(0, v_ip_message_limit - v_ip_messages));
  end if;
  if p_ip_hash is not null and v_ip_tokens + p_reserved_tokens > v_ip_token_limit then
    return jsonb_build_object('allowed', false, 'reason', 'ip_tokens', 'retry_after_seconds', v_retry_after, 'ip_remaining_messages', greatest(0, v_ip_message_limit - v_ip_messages));
  end if;

  update public.ai_usage_daily set messages_used = messages_used + 1, reserved_tokens = reserved_tokens + p_reserved_tokens, is_anonymous = v_is_anonymous, last_used_at = now()
  where usage_date = timezone('utc', now())::date and bucket_scope = 'user' and bucket_key = p_user_id::text;
  if p_ip_hash is not null then
    update public.ai_usage_daily set messages_used = messages_used + 1, reserved_tokens = reserved_tokens + p_reserved_tokens, is_anonymous = v_is_anonymous, last_used_at = now()
    where usage_date = timezone('utc', now())::date and bucket_scope = 'ip' and bucket_key = p_ip_hash;
  end if;

  return jsonb_build_object('allowed', true, 'user_remaining_messages', greatest(0, v_user_message_limit - v_user_messages - 1), 'ip_remaining_messages', case when p_ip_hash is null then null else greatest(0, v_ip_message_limit - v_ip_messages - 1) end);
end;
$function$;

CREATE OR REPLACE FUNCTION public.consume_ai_web_search_quota (
  p_user_id      uuid,
  p_ip_hash      text,
  p_is_anonymous boolean,
  p_units        integer
)
  RETURNS jsonb
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
declare
  v_config public.ai_quota_config%rowtype;
  v_user_used integer;
  v_ip_used integer;
  v_user_limit integer;
  v_ip_limit integer;
  v_retry_after integer;
begin
  if auth.uid() is null or auth.uid() is distinct from p_user_id then
    raise exception 'AI web search quota user mismatch' using errcode = '42501';
  end if;

  if p_units < 1 or p_units > 2 then
    raise exception 'AI web search quota units are invalid' using errcode = '22023';
  end if;

  select * into v_config
  from public.ai_quota_config
  where singleton is true;

  if not found then
    raise exception 'AI quota configuration is missing' using errcode = 'P0001';
  end if;

  v_user_limit := case when p_is_anonymous
    then v_config.anonymous_daily_web_searches
    else v_config.authenticated_daily_web_searches end;
  v_ip_limit := case when p_is_anonymous
    then v_config.anonymous_ip_daily_web_searches
    else v_config.authenticated_ip_daily_web_searches end;
  v_retry_after := greatest(1, extract(epoch from (
    date_trunc('day', timezone('utc', now())) + interval '1 day' - timezone('utc', now())
  ))::integer);

  insert into public.ai_usage_daily (
    usage_date, bucket_scope, bucket_key, user_id, is_anonymous
  ) values (
    timezone('utc', now())::date, 'user', p_user_id::text, p_user_id, p_is_anonymous
  ) on conflict (usage_date, bucket_scope, bucket_key) do nothing;

  select web_searches_used into v_user_used
  from public.ai_usage_daily
  where usage_date = timezone('utc', now())::date
    and bucket_scope = 'user'
    and bucket_key = p_user_id::text
  for update;

  if p_ip_hash is not null then
    insert into public.ai_usage_daily (
      usage_date, bucket_scope, bucket_key, ip_hash, is_anonymous
    ) values (
      timezone('utc', now())::date, 'ip', p_ip_hash, p_ip_hash, p_is_anonymous
    ) on conflict (usage_date, bucket_scope, bucket_key) do nothing;

    select web_searches_used into v_ip_used
    from public.ai_usage_daily
    where usage_date = timezone('utc', now())::date
      and bucket_scope = 'ip'
      and bucket_key = p_ip_hash
    for update;
  end if;

  if v_user_used + p_units > v_user_limit then
    return jsonb_build_object(
      'allowed', false,
      'reason', 'user_web_searches',
      'retry_after_seconds', v_retry_after,
      'user_remaining_searches', greatest(0, v_user_limit - v_user_used),
      'ip_remaining_searches', case when p_ip_hash is null then null else greatest(0, v_ip_limit - coalesce(v_ip_used, 0)) end
    );
  end if;

  if p_ip_hash is not null and v_ip_used + p_units > v_ip_limit then
    return jsonb_build_object(
      'allowed', false,
      'reason', 'ip_web_searches',
      'retry_after_seconds', v_retry_after,
      'user_remaining_searches', greatest(0, v_user_limit - v_user_used),
      'ip_remaining_searches', greatest(0, v_ip_limit - v_ip_used)
    );
  end if;

  update public.ai_usage_daily
  set web_searches_used = web_searches_used + p_units,
      is_anonymous = p_is_anonymous,
      last_used_at = now()
  where usage_date = timezone('utc', now())::date
    and bucket_scope = 'user'
    and bucket_key = p_user_id::text;

  if p_ip_hash is not null then
    update public.ai_usage_daily
    set web_searches_used = web_searches_used + p_units,
        is_anonymous = p_is_anonymous,
        last_used_at = now()
    where usage_date = timezone('utc', now())::date
      and bucket_scope = 'ip'
      and bucket_key = p_ip_hash;
  end if;

  return jsonb_build_object(
    'allowed', true,
    'user_remaining_searches', greatest(0, v_user_limit - v_user_used - p_units),
    'ip_remaining_searches', case when p_ip_hash is null then null else greatest(0, v_ip_limit - v_ip_used - p_units) end
  );
end;
$function$;

CREATE OR REPLACE FUNCTION public.create_ai_conversation (
  p_user_id uuid,
  p_title   text
)
  RETURNS uuid
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
declare
  v_id uuid;
  v_title text := left(regexp_replace(coalesce(trim(p_title), ''), '\s+', ' ', 'g'), 80);
begin
  if p_user_id is null then
    raise exception 'ai_conversation_user_required' using errcode = '22023';
  end if;

  if char_length(v_title) = 0 then
    v_title := 'Nuevo chat';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text, 7107));

  if (select count(*) from public.ai_conversations where user_id = p_user_id) >= 10 then
    raise exception 'ai_conversation_limit' using errcode = 'P0001';
  end if;

  insert into public.ai_conversations (user_id, title)
  values (p_user_id, v_title)
  returning id into v_id;

  return v_id;
end;
$function$;

CREATE OR REPLACE FUNCTION public.create_ai_pending_action (
  p_action_type    text,
  p_payload        jsonb,
  p_payload_digest text,
  p_expires_at     timestamp with time zone
)
  RETURNS uuid
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
declare
  v_id uuid;
begin
  if auth.uid() is null
    or coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) then
    raise exception 'AI pending action requires a permanent account' using errcode = '42501';
  end if;

  if p_action_type not in ('create_combo', 'create_build', 'set_custom_price')
    or p_payload_digest !~ '^[a-f0-9]{64}$'
    or p_expires_at <= now()
    or p_expires_at > now() + interval '15 minutes' then
    raise exception 'AI pending action is invalid' using errcode = '22023';
  end if;

  insert into public.ai_pending_actions (
    user_id, action_type, payload, payload_digest, expires_at
  ) values (
    auth.uid(), p_action_type, p_payload, lower(p_payload_digest), p_expires_at
  ) returning id into v_id;

  return v_id;
end;
$function$;

CREATE OR REPLACE FUNCTION public.get_ai_admin_usage (
  p_days integer DEFAULT 7
)
  RETURNS jsonb
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
declare
  v_days integer := greatest(1, least(coalesce(p_days, 7), 31));
  v_role text;
begin
  v_role := auth.jwt() -> 'app_metadata' ->> 'role';

  if v_role is distinct from 'admin' then
    raise exception 'AI admin access denied' using errcode = '42501';
  end if;

  return jsonb_build_object(
    'days', v_days,
    'config', coalesce((
      select to_jsonb(config_row) - 'singleton'
      from public.ai_quota_config as config_row
      where config_row.singleton is true
    ), '{}'::jsonb),
    'daily_usage', coalesce((
      select jsonb_agg(to_jsonb(daily_row) order by daily_row.usage_date desc)
      from (
        select
          usage_date,
          coalesce(sum(messages_used) filter (where bucket_scope = 'user'), 0) as user_messages,
          coalesce(sum(reserved_tokens) filter (where bucket_scope = 'user'), 0) as user_reserved_tokens,
          count(*) filter (where bucket_scope = 'ip') as ip_buckets
        from public.ai_usage_daily
        where usage_date >= current_date - (v_days - 1)
        group by usage_date
      ) as daily_row
    ), '[]'::jsonb),
    'providers', coalesce((
      select jsonb_agg(to_jsonb(provider_row) order by provider_row.requests desc)
      from (
        select
          provider,
          status,
          count(*) as requests,
          coalesce(sum(input_tokens + output_tokens), 0) as tokens,
          round(avg(duration_ms)) as average_duration_ms
        from public.ai_action_logs
        where created_at >= now() - make_interval(days => v_days)
        group by provider, status
      ) as provider_row
    ), '[]'::jsonb),
    'errors', coalesce((
      select jsonb_agg(to_jsonb(error_row) order by error_row.failures desc)
      from (
        select
          coalesce(error_code, 'unknown') as error_code,
          count(*) as failures
        from public.ai_action_logs
        where created_at >= now() - make_interval(days => v_days)
          and status = 'error'
        group by error_code
      ) as error_row
    ), '[]'::jsonb),
    'top_ip_buckets', coalesce((
      select jsonb_agg(to_jsonb(ip_row) order by ip_row.requests desc)
      from (
        select ip_hash, count(*) as requests
        from public.ai_action_logs
        where created_at >= now() - make_interval(days => v_days)
          and ip_hash is not null
        group by ip_hash
        order by count(*) desc
        limit 10
      ) as ip_row
    ), '[]'::jsonb)
  );
end;
$function$;

CREATE OR REPLACE FUNCTION public.get_my_ai_quota_status()
  RETURNS jsonb
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
declare
  v_user_id uuid := auth.uid();
  v_is_anonymous boolean := coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false);
  v_config public.ai_quota_config%rowtype;
  v_messages_used integer := 0;
  v_tokens_used bigint := 0;
  v_message_limit integer;
  v_token_limit bigint;
  v_reset_at timestamptz;
begin
  if v_user_id is null then
    raise exception 'AI quota status requires an authenticated session' using errcode = '42501';
  end if;

  select * into v_config
  from public.ai_quota_config
  where singleton is true;

  if not found then
    raise exception 'AI quota configuration is missing' using errcode = 'P0001';
  end if;

  v_message_limit := case when v_is_anonymous
    then v_config.anonymous_daily_messages
    else v_config.authenticated_daily_messages end;
  v_token_limit := case when v_is_anonymous
    then v_config.anonymous_daily_tokens
    else v_config.authenticated_daily_tokens end;

  select messages_used, reserved_tokens
    into v_messages_used, v_tokens_used
  from public.ai_usage_daily
  where usage_date = timezone('utc', now())::date
    and bucket_scope = 'user'
    and bucket_key = v_user_id::text;

  v_messages_used := coalesce(v_messages_used, 0);
  v_tokens_used := coalesce(v_tokens_used, 0);
  v_reset_at := (date_trunc('day', now() at time zone 'utc') + interval '1 day') at time zone 'utc';

  return jsonb_build_object(
    'is_anonymous', v_is_anonymous,
    'messages_used', v_messages_used,
    'messages_limit', v_message_limit,
    'messages_remaining', greatest(0, v_message_limit - v_messages_used),
    'tokens_used', v_tokens_used,
    'tokens_limit', v_token_limit,
    'tokens_remaining', greatest(0, v_token_limit - v_tokens_used),
    'reset_at', v_reset_at
  );
end;
$function$;

CREATE OR REPLACE FUNCTION public.record_ai_request (
  p_user_id       uuid,
  p_is_anonymous  boolean,
  p_ip_hash       text,
  p_provider      text,
  p_model         text,
  p_duration_ms   integer,
  p_input_tokens  integer,
  p_output_tokens integer,
  p_tool_calls    integer,
  p_status        text,
  p_error_code    text    DEFAULT NULL::text
)
  RETURNS void
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
begin
  if auth.uid() is null or auth.uid() is distinct from p_user_id then
    raise exception 'AI telemetry user mismatch' using errcode = '42501';
  end if;

  if coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) is distinct from p_is_anonymous then
    raise exception 'AI telemetry actor mismatch' using errcode = '42501';
  end if;

  insert into public.ai_action_logs (
    user_id, is_anonymous, ip_hash, provider, model, duration_ms,
    input_tokens, output_tokens, tool_calls, status, error_code
  ) values (
    p_user_id, p_is_anonymous, p_ip_hash, p_provider, left(p_model, 160),
    greatest(p_duration_ms, 0), greatest(p_input_tokens, 0), greatest(p_output_tokens, 0),
    greatest(p_tool_calls, 0), p_status, left(p_error_code, 100)
  );
end;
$function$;

CREATE OR REPLACE FUNCTION public.record_ai_request_v2 (
  p_user_id              uuid,
  p_is_anonymous         boolean,
  p_ip_hash              text,
  p_provider             text,
  p_model                text,
  p_duration_ms          integer,
  p_input_tokens         integer,
  p_output_tokens        integer,
  p_tool_calls           integer,
  p_status               text,
  p_error_code           text     DEFAULT NULL::text,
  p_failure_stage        text     DEFAULT NULL::text,
  p_provider_http_status smallint DEFAULT NULL::smallint,
  p_finish_reason        text     DEFAULT NULL::text
)
  RETURNS void
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
begin
  if auth.uid() is null or auth.uid() is distinct from p_user_id then
    raise exception 'AI telemetry user mismatch' using errcode = '42501';
  end if;

  if coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) is distinct from p_is_anonymous then
    raise exception 'AI telemetry actor mismatch' using errcode = '42501';
  end if;

  insert into public.ai_action_logs (
    user_id, is_anonymous, ip_hash, provider, model, duration_ms,
    input_tokens, output_tokens, tool_calls, status, error_code,
    failure_stage, provider_http_status, finish_reason
  ) values (
    p_user_id, p_is_anonymous, p_ip_hash, p_provider, left(p_model, 160),
    greatest(p_duration_ms, 0), greatest(p_input_tokens, 0), greatest(p_output_tokens, 0),
    greatest(p_tool_calls, 0), p_status, left(p_error_code, 100),
    left(p_failure_stage, 40),
    case when p_provider_http_status between 100 and 599 then p_provider_http_status else null end,
    left(p_finish_reason, 40)
  );
end;
$function$;

CREATE OR REPLACE FUNCTION public.reorder_catalog_categories (
  p_kind       text,
  p_categories text[]
)
  RETURNS void
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
declare
  v_requested_count integer := coalesce(array_length(p_categories, 1), 0);
  v_distinct_count integer;
  v_existing_count integer;
  v_matching_count integer;
  v_position integer;
begin
  if (auth.jwt() -> 'app_metadata' ->> 'role') is distinct from 'admin' then
    raise exception 'Catalog admin access denied' using errcode = '42501';
  end if;

  if p_kind not in ('builds', 'combos') then
    raise exception 'Invalid catalog kind' using errcode = '22023';
  end if;

  select count(distinct category_name)::integer
  into v_distinct_count
  from unnest(coalesce(p_categories, '{}'::text[])) as requested(category_name);

  select count(*)::integer
  into v_existing_count
  from public.catalog_category_orders
  where catalog_kind = p_kind;

  select count(*)::integer
  into v_matching_count
  from public.catalog_category_orders
  where catalog_kind = p_kind
    and category = any(coalesce(p_categories, '{}'::text[]));

  if v_requested_count <> v_existing_count
     or v_distinct_count <> v_requested_count
     or v_matching_count <> v_requested_count then
    raise exception 'The submitted category order is incomplete or invalid'
      using errcode = '22023';
  end if;

  update public.catalog_category_orders
  set sort_order = sort_order + 1000000
  where catalog_kind = p_kind;

  if v_requested_count > 0 then
    for v_position in 1..v_requested_count loop
      update public.catalog_category_orders
      set sort_order = v_position
      where catalog_kind = p_kind
        and category = p_categories[v_position];
    end loop;
  end if;
end;
$function$;

CREATE OR REPLACE FUNCTION public.reorder_catalog_items (
  p_kind text,
  p_ids  uuid[]
)
  RETURNS void
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
declare
  v_table text;
  v_requested_count integer := coalesce(array_length(p_ids, 1), 0);
  v_distinct_count integer;
  v_existing_count integer;
  v_matching_count integer;
  v_position integer;
begin
  if (auth.jwt() -> 'app_metadata' ->> 'role') is distinct from 'admin' then
    raise exception 'Catalog admin access denied' using errcode = '42501';
  end if;

  if p_kind not in ('builds', 'combos') then
    raise exception 'Invalid catalog kind' using errcode = '22023';
  end if;

  v_table := p_kind;

  select count(distinct item_id)::integer
  into v_distinct_count
  from unnest(coalesce(p_ids, '{}'::uuid[])) as requested(item_id);

  execute format('select count(*)::integer from public.%I', v_table)
  into v_existing_count;

  execute format('select count(*)::integer from public.%I where id = any($1)', v_table)
  into v_matching_count
  using coalesce(p_ids, '{}'::uuid[]);

  if v_requested_count <> v_existing_count
     or v_distinct_count <> v_requested_count
     or v_matching_count <> v_requested_count then
    raise exception 'The submitted catalog order is incomplete or contains invalid IDs'
      using errcode = '22023';
  end if;

  if v_requested_count > 0 then
    for v_position in 1..v_requested_count loop
      execute format('update public.%I set sort_order = $1 where id = $2', v_table)
      using v_position, p_ids[v_position];
    end loop;
  end if;
end;
$function$;

CREATE OR REPLACE FUNCTION public.reorder_catalog_items_by_category (
  p_kind     text,
  p_category text,
  p_ids      uuid[]
)
  RETURNS void
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
declare
  v_table text;
  v_requested_count integer := coalesce(array_length(p_ids, 1), 0);
  v_distinct_count integer;
  v_existing_count integer;
  v_matching_count integer;
  v_position integer;
begin
  if (auth.jwt() -> 'app_metadata' ->> 'role') is distinct from 'admin' then
    raise exception 'Catalog admin access denied' using errcode = '42501';
  end if;

  if p_kind not in ('builds', 'combos') or p_category is null or trim(p_category) = '' then
    raise exception 'Invalid catalog category' using errcode = '22023';
  end if;

  v_table := p_kind;

  select count(distinct item_id)::integer
  into v_distinct_count
  from unnest(coalesce(p_ids, '{}'::uuid[])) as requested(item_id);

  execute format(
    'select count(*)::integer from public.%I where coalesce(nullif(trim(category), ''''), ''Sin categoría'') = $1',
    v_table
  ) into v_existing_count using p_category;

  execute format(
    'select count(*)::integer from public.%I where coalesce(nullif(trim(category), ''''), ''Sin categoría'') = $1 and id = any($2)',
    v_table
  ) into v_matching_count using p_category, coalesce(p_ids, '{}'::uuid[]);

  if v_requested_count <> v_existing_count
     or v_distinct_count <> v_requested_count
     or v_matching_count <> v_requested_count then
    raise exception 'The submitted item order is incomplete or invalid'
      using errcode = '22023';
  end if;

  execute format(
    'update public.%I set sort_order = sort_order + 1000000 where coalesce(nullif(trim(category), ''''), ''Sin categoría'') = $1',
    v_table
  ) using p_category;

  if v_requested_count > 0 then
    for v_position in 1..v_requested_count loop
      execute format('update public.%I set sort_order = $1 where id = $2', v_table)
      using v_position, p_ids[v_position];
    end loop;
  end if;
end;
$function$;

CREATE OR REPLACE FUNCTION public.set_user_ai_chat_settings_updated_at()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SET search_path TO 'public'
  AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.set_user_ai_web_search_settings_updated_at()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.settle_ai_quota (
  p_user_id         uuid,
  p_ip_hash         text,
  p_reserved_tokens integer,
  p_actual_tokens   integer
)
  RETURNS void
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
begin
  if auth.uid() is null or auth.uid() is distinct from p_user_id then
    raise exception 'AI quota settlement user mismatch' using errcode = '42501';
  end if;

  if p_reserved_tokens < 0 or p_reserved_tokens > 20000
    or p_actual_tokens < 0 or p_actual_tokens > 1000000 then
    raise exception 'AI quota settlement is invalid' using errcode = '22023';
  end if;

  update public.ai_usage_daily
  set reserved_tokens = greatest(0, reserved_tokens - p_reserved_tokens + p_actual_tokens),
      last_used_at = now()
  where usage_date = timezone('utc', now())::date
    and bucket_scope = 'user'
    and bucket_key = p_user_id::text;

  if p_ip_hash is not null then
    update public.ai_usage_daily
    set reserved_tokens = greatest(0, reserved_tokens - p_reserved_tokens + p_actual_tokens),
        last_used_at = now()
    where usage_date = timezone('utc', now())::date
      and bucket_scope = 'ip'
      and bucket_key = p_ip_hash;
  end if;
end;
$function$;

ALTER TABLE "public"."ai_action_logs"
  ADD CONSTRAINT "ai_action_logs_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."ai_conversation_messages"
  ADD CONSTRAINT "ai_conversation_messages_conversation_id_fkey" FOREIGN KEY (conversation_id) REFERENCES public.ai_conversations(id) ON DELETE CASCADE;

ALTER TABLE "public"."ai_conversations"
  ADD CONSTRAINT "ai_conversations_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."ai_pending_actions"
  ADD CONSTRAINT "ai_pending_actions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."ai_usage_daily"
  ADD CONSTRAINT "ai_usage_daily_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."created_builds"
  ADD CONSTRAINT "created_builds_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."created_combos"
  ADD CONSTRAINT "created_combos_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."home_comparison_items"
  ADD CONSTRAINT "home_comparison_items_build_id_fkey" FOREIGN KEY (build_id) REFERENCES public.builds(id) ON DELETE CASCADE;

ALTER TABLE "public"."home_comparison_items"
  ADD CONSTRAINT "home_comparison_items_combo_id_fkey" FOREIGN KEY (combo_id) REFERENCES public.combos(id) ON DELETE CASCADE;

ALTER TABLE "public"."home_comparison_items"
  ADD CONSTRAINT "home_comparison_items_comparison_id_fkey" FOREIGN KEY (comparison_id) REFERENCES public.home_comparisons(id) ON DELETE CASCADE;

ALTER TABLE "public"."home_section_items"
  ADD CONSTRAINT "home_section_items_build_id_fkey" FOREIGN KEY (build_id) REFERENCES public.builds(id) ON DELETE CASCADE;

ALTER TABLE "public"."home_section_items"
  ADD CONSTRAINT "home_section_items_combo_id_fkey" FOREIGN KEY (combo_id) REFERENCES public.combos(id) ON DELETE CASCADE;

ALTER TABLE "public"."home_comparisons"
  ADD CONSTRAINT "home_comparisons_section_id_fkey" FOREIGN KEY (section_id) REFERENCES public.home_sections(id) ON DELETE CASCADE;

ALTER TABLE "public"."home_section_items"
  ADD CONSTRAINT "home_section_items_section_id_fkey" FOREIGN KEY (section_id) REFERENCES public.home_sections(id) ON DELETE CASCADE;

ALTER TABLE "public"."builds"
  ADD CONSTRAINT "builds_cpu_id_fkey" FOREIGN KEY (cpu_id) REFERENCES public.products(id);

ALTER TABLE "public"."builds"
  ADD CONSTRAINT "builds_gpu_id_fkey" FOREIGN KEY (gpu_id) REFERENCES public.products(id);

ALTER TABLE "public"."builds"
  ADD CONSTRAINT "builds_motherboard_id_fkey" FOREIGN KEY (motherboard_id) REFERENCES public.products(id);

ALTER TABLE "public"."builds"
  ADD CONSTRAINT "builds_psu_id_fkey" FOREIGN KEY (psu_id) REFERENCES public.products(id);

ALTER TABLE "public"."builds"
  ADD CONSTRAINT "builds_ram_id_fkey" FOREIGN KEY (ram_id) REFERENCES public.products(id);

ALTER TABLE "public"."builds"
  ADD CONSTRAINT "builds_storage_id_fkey" FOREIGN KEY (storage_id) REFERENCES public.products(id);

ALTER TABLE "public"."combos"
  ADD CONSTRAINT "combos_cpu_id_fkey" FOREIGN KEY (cpu_id) REFERENCES public.products(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "public"."combos"
  ADD CONSTRAINT "combos_gpu_id_fkey" FOREIGN KEY (gpu_id) REFERENCES public.products(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "public"."combos"
  ADD CONSTRAINT "combos_ram_id_fkey" FOREIGN KEY (ram_id) REFERENCES public.products(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "public"."created_builds"
  ADD CONSTRAINT "created_builds_cpu_id_fkey" FOREIGN KEY (cpu_id) REFERENCES public.products(id);

ALTER TABLE "public"."created_builds"
  ADD CONSTRAINT "created_builds_gpu_id_fkey" FOREIGN KEY (gpu_id) REFERENCES public.products(id);

ALTER TABLE "public"."created_builds"
  ADD CONSTRAINT "created_builds_motherboard_id_fkey" FOREIGN KEY (motherboard_id) REFERENCES public.products(id);

ALTER TABLE "public"."created_builds"
  ADD CONSTRAINT "created_builds_psu_id_fkey" FOREIGN KEY (psu_id) REFERENCES public.products(id);

ALTER TABLE "public"."created_builds"
  ADD CONSTRAINT "created_builds_ram_id_fkey" FOREIGN KEY (ram_id) REFERENCES public.products(id);

ALTER TABLE "public"."created_builds"
  ADD CONSTRAINT "created_builds_storage_id_fkey" FOREIGN KEY (storage_id) REFERENCES public.products(id);

ALTER TABLE "public"."created_combos"
  ADD CONSTRAINT "created_combos_cpu_id_fkey" FOREIGN KEY (cpu_id) REFERENCES public.products(id);

ALTER TABLE "public"."created_combos"
  ADD CONSTRAINT "created_combos_gpu_id_fkey" FOREIGN KEY (gpu_id) REFERENCES public.products(id);

ALTER TABLE "public"."created_combos"
  ADD CONSTRAINT "created_combos_ram_id_fkey" FOREIGN KEY (ram_id) REFERENCES public.products(id);

ALTER TABLE "public"."home_comparison_items"
  ADD CONSTRAINT "home_comparison_items_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;

ALTER TABLE "public"."home_section_items"
  ADD CONSTRAINT "home_section_items_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;

ALTER TABLE "public"."saved_builds"
  ADD CONSTRAINT "saved_builds_build_id_fkey" FOREIGN KEY (build_id) REFERENCES public.builds(id) ON DELETE CASCADE;

ALTER TABLE "public"."saved_builds"
  ADD CONSTRAINT "saved_builds_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."saved_combos"
  ADD CONSTRAINT "saved_combos_combo_id_fkey" FOREIGN KEY (combo_id) REFERENCES public.combos(id) ON DELETE CASCADE;

ALTER TABLE "public"."saved_combos"
  ADD CONSTRAINT "saved_combos_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."saved_products"
  ADD CONSTRAINT "saved_products_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;

ALTER TABLE "public"."saved_products"
  ADD CONSTRAINT "saved_products_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."user_ai_chat_settings"
  ADD CONSTRAINT "user_ai_chat_settings_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."user_ai_web_search_settings"
  ADD CONSTRAINT "user_ai_web_search_settings_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

CREATE VIEW "public"."products_with_priority" AS  SELECT id,
    slug,
    market_segment,
    name,
    brand,
    type,
    category,
    description,
    price_base_usd,
    release_date,
    release_year,
    compatibility,
    specs,
    technologies,
    benchmarks,
    tags,
    created_at,
    price_base_eur,
        CASE
            WHEN (upper(TRIM(BOTH FROM type)) = 'CPU'::text) THEN 1
            WHEN (upper(TRIM(BOTH FROM type)) = 'GPU'::text) THEN 1
            ELSE 2
        END AS priority,
    price_eur,
    price_usd
   FROM public.products;

CREATE INDEX ai_action_logs_created_at_idx ON public.ai_action_logs USING btree (created_at DESC);

CREATE INDEX ai_action_logs_user_created_at_idx ON public.ai_action_logs USING btree (user_id, created_at DESC);

CREATE INDEX ai_conversation_messages_conversation_id_idx ON public.ai_conversation_messages USING btree (conversation_id, id);

CREATE INDEX ai_conversations_user_last_message_idx ON public.ai_conversations USING btree (user_id, last_message_at DESC);

CREATE INDEX ai_pending_actions_expiry_idx ON public.ai_pending_actions USING btree (expires_at)
  WHERE (consumed_at IS NULL);

CREATE INDEX ai_pending_actions_user_created_idx ON public.ai_pending_actions USING btree (user_id, created_at DESC);

CREATE INDEX ai_usage_daily_user_date_idx ON public.ai_usage_daily USING btree (user_id, usage_date)
  WHERE (user_id IS NOT NULL);

CREATE INDEX builds_catalog_order_idx ON public.builds USING btree (is_active, sort_order, created_at DESC);

CREATE INDEX combos_catalog_order_idx ON public.combos USING btree (is_active, sort_order, created_at DESC);

CREATE INDEX created_builds_user_created_at_idx ON public.created_builds USING btree (user_id, created_at DESC);

CREATE INDEX home_comparison_items_comparison_order_idx ON public.home_comparison_items USING btree (comparison_id, sort_order, created_at);

CREATE INDEX home_comparisons_section_order_idx ON public.home_comparisons USING btree (section_id, is_active, sort_order, created_at);

CREATE INDEX home_section_items_section_order_idx ON public.home_section_items USING btree (section_id, sort_order, created_at);

CREATE INDEX home_sections_public_order_idx ON public.home_sections USING btree (is_active, sort_order, created_at);

CREATE INDEX saved_combos_combo_id_idx ON public.saved_combos USING btree (combo_id);

CREATE INDEX saved_products_product_id_idx ON public.saved_products USING btree (product_id);

CREATE TRIGGER user_ai_chat_settings_updated_at
  BEFORE UPDATE ON public.user_ai_chat_settings
  FOR EACH ROW
  EXECUTE FUNCTION public.set_user_ai_chat_settings_updated_at();

CREATE TRIGGER user_ai_web_search_settings_updated_at
  BEFORE UPDATE ON public.user_ai_web_search_settings
  FOR EACH ROW
  EXECUTE FUNCTION public.set_user_ai_web_search_settings_updated_at();

CREATE POLICY "Anyone can view active builds" ON "public"."builds"
  FOR SELECT
  TO "anon", "authenticated"
  USING ((is_active = true));

CREATE POLICY "Anyone can read catalog category order" ON "public"."catalog_category_orders"
  FOR SELECT
  TO "anon", "authenticated"
  USING (true);

CREATE POLICY "Permitir lectura pública de combos" ON "public"."combos"
  FOR SELECT
  TO "anon", "authenticated"
  USING (true);

CREATE POLICY "Users can create their builds" ON "public"."created_builds"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can delete their created builds" ON "public"."created_builds"
  FOR DELETE
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can update their created builds" ON "public"."created_builds"
  FOR UPDATE
  TO PUBLIC
  USING ((auth.uid() = user_id))
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can view their created builds" ON "public"."created_builds"
  FOR SELECT
  TO PUBLIC
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can create combos" ON "public"."created_combos"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can delete their created combos" ON "public"."created_combos"
  FOR DELETE
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can update their created combos" ON "public"."created_combos"
  FOR UPDATE
  TO "authenticated"
  USING ((auth.uid() = user_id))
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can view their created combos" ON "public"."created_combos"
  FOR SELECT
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "Anyone can read home comparison items" ON "public"."home_comparison_items"
  FOR SELECT
  TO "anon", "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM (public.home_comparisons comparison
     JOIN public.home_sections section ON ((section.id = comparison.section_id)))
  WHERE ((comparison.id = home_comparison_items.comparison_id) AND (comparison.is_active = true) AND (section.is_active = true)))));

CREATE POLICY "Anyone can read public home comparisons" ON "public"."home_comparisons"
  FOR SELECT
  TO "anon", "authenticated"
  USING (((is_active = true) AND (EXISTS ( SELECT 1
   FROM public.home_sections
  WHERE ((home_sections.id = home_comparisons.section_id) AND (home_sections.is_active = true))))));

CREATE POLICY "Anyone can read public home hero" ON "public"."home_hero"
  FOR SELECT
  TO "anon", "authenticated"
  USING ((is_active = true));

CREATE POLICY "Anyone can read home section items" ON "public"."home_section_items"
  FOR SELECT
  TO "anon", "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.home_sections
  WHERE ((home_sections.id = home_section_items.section_id) AND (home_sections.is_active = true)))));

CREATE POLICY "Anyone can read public home sections" ON "public"."home_sections"
  FOR SELECT
  TO "anon", "authenticated"
  USING ((is_active = true));

CREATE POLICY "Permitir lectura pública" ON "public"."products"
  FOR SELECT
  TO "anon", "authenticated"
  USING (true);

CREATE POLICY "Users can remove their saved builds" ON "public"."saved_builds"
  FOR DELETE
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can save builds" ON "public"."saved_builds"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can view their saved builds" ON "public"."saved_builds"
  FOR SELECT
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can remove their saved combos" ON "public"."saved_combos"
  FOR DELETE
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can save combos" ON "public"."saved_combos"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can view their saved combos" ON "public"."saved_combos"
  FOR SELECT
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can remove their saved products" ON "public"."saved_products"
  FOR DELETE
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can save products" ON "public"."saved_products"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can view their saved products" ON "public"."saved_products"
  FOR SELECT
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can delete their web search settings" ON "public"."user_ai_web_search_settings"
  FOR DELETE
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can insert their web search settings" ON "public"."user_ai_web_search_settings"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can read their web search settings" ON "public"."user_ai_web_search_settings"
  FOR SELECT
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can update their web search settings" ON "public"."user_ai_web_search_settings"
  FOR UPDATE
  TO "authenticated"
  USING ((auth.uid() = user_id))
  WITH CHECK ((auth.uid() = user_id));

REVOKE ALL ON FUNCTION "public"."append_ai_conversation_turn"(uuid, uuid, text, text, jsonb, jsonb, text) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."append_ai_conversation_turn"(uuid, uuid, text, text, jsonb, jsonb, text) TO "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."cleanup_ai_telemetry"(integer) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."cleanup_ai_telemetry"(integer) TO "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."consume_ai_pending_action"(uuid, text) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."consume_ai_pending_action"(uuid, text) TO "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."consume_ai_quota"(uuid, text, boolean, integer) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."consume_ai_quota"(uuid, text, boolean, integer) TO "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."consume_ai_web_search_quota"(uuid, text, boolean, integer) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."consume_ai_web_search_quota"(uuid, text, boolean, integer) TO "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."create_ai_conversation"(uuid, text) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."create_ai_conversation"(uuid, text) TO "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."create_ai_pending_action"(text, jsonb, text, timestamp WITH time zone) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."create_ai_pending_action"(text, jsonb, text, timestamp WITH time zone) TO "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."get_ai_admin_usage"(integer) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."get_ai_admin_usage"(integer) TO "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."get_my_ai_quota_status"() FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."get_my_ai_quota_status"() TO "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."record_ai_request"(uuid, boolean, text, text, text, integer, integer, integer, integer, text, text) FROM PUBLIC;

GRANT EXECUTE
  ON FUNCTION "public"."record_ai_request"(uuid, boolean, text, text, text, integer, integer, integer, integer, text, text)
  TO "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."record_ai_request_v2"(uuid, boolean, text, text, text, integer, integer, integer, integer, text, text, text, smallint, text) FROM PUBLIC;

GRANT EXECUTE
  ON FUNCTION "public"."record_ai_request_v2"(uuid, boolean, text, text, text, integer, integer, integer, integer, text, text, text, smallint, text)
  TO "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."reorder_catalog_categories"(text, text[]) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."reorder_catalog_categories"(text, text[]) TO "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."reorder_catalog_items"(text, uuid[]) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."reorder_catalog_items"(text, uuid[]) TO "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."reorder_catalog_items_by_category"(text, text, uuid[]) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."reorder_catalog_items_by_category"(text, text, uuid[]) TO "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."set_user_ai_chat_settings_updated_at"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."set_user_ai_web_search_settings_updated_at"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."settle_ai_quota"(uuid, text, integer, integer) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."settle_ai_quota"(uuid, text, integer, integer) TO "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."ai_action_logs" TO "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."ai_conversation_messages" TO "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."ai_conversations" TO "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."ai_pending_actions" TO "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."ai_quota_config" TO "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."ai_usage_daily" TO "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."builds" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."catalog_category_orders" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."combos" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."created_builds" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."created_combos" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."games" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."home_comparison_items" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."home_comparisons" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."home_hero" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."home_section_items" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."home_sections" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."products" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE
  ON TABLE "public"."products_gpu_compatibility_backup_20260813"
  TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."saved_builds" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."saved_combos" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."saved_products" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_ai_chat_settings" TO "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_ai_web_search_settings" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."products_with_priority" TO "anon", "authenticated", "postgres", "service_role";
