-- CoreX AI Fase 7: BYOK de IA e historial de conversaciones.
-- Las tablas no se exponen al navegador. La aplicación las usa desde el
-- cliente de servidor con la clave secreta de Supabase.

create table if not exists public.user_ai_chat_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  credential_mode text not null default 'project'
    check (credential_mode in ('project', 'byok')),
  preferred_provider text not null default 'openrouter'
    check (preferred_provider in ('groq', 'openrouter')),
  preferred_model text not null default '',
  groq_api_key_ciphertext text,
  groq_key_hint text,
  openrouter_api_key_ciphertext text,
  openrouter_key_hint text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ai_conversations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 80),
  state jsonb not null default '{}'::jsonb,
  message_count integer not null default 0 check (message_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_message_at timestamptz not null default now()
);

create table if not exists public.ai_conversation_messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.ai_conversations(id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null check (char_length(content) between 1 and 12000),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists ai_conversations_user_last_message_idx
  on public.ai_conversations (user_id, last_message_at desc);

create index if not exists ai_conversation_messages_conversation_id_idx
  on public.ai_conversation_messages (conversation_id, id);

alter table public.user_ai_chat_settings enable row level security;
alter table public.ai_conversations enable row level security;
alter table public.ai_conversation_messages enable row level security;

-- No se concede acceso directo a anon/authenticated. Las operaciones de la
-- aplicación usan el cliente server-only con la clave secreta de Supabase.
revoke all on table public.user_ai_chat_settings from anon, authenticated;
revoke all on table public.ai_conversations from anon, authenticated;
revoke all on table public.ai_conversation_messages from anon, authenticated;

-- La creación y el append se hacen en RPC atómicas para que el límite de diez
-- chats no pueda rebasarse por dos peticiones simultáneas del mismo usuario.
create or replace function public.create_ai_conversation(
  p_user_id uuid,
  p_title text
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
  v_title text := left(regexp_replace(coalesce(trim(p_title), ''), '\s+', ' ', 'g'), 80);
begin
  if p_user_id is null then
    raise exception 'ai_conversation_user_required' using errcode = '22023';
  end if;

  if char_length(v_title) = 0 then
    v_title := 'Nuevo chat';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text, 7107));

  if (select count(*) from public.ai_conversations where user_id = p_user_id) >= 10 then
    raise exception 'ai_conversation_limit' using errcode = 'P0001';
  end if;

  insert into public.ai_conversations (user_id, title)
  values (p_user_id, v_title)
  returning id into v_id;

  return v_id;
end;
$$;

create or replace function public.append_ai_conversation_turn(
  p_user_id uuid,
  p_conversation_id uuid,
  p_user_content text,
  p_assistant_content text,
  p_metadata jsonb default '{}'::jsonb,
  p_state jsonb default '{}'::jsonb,
  p_title text default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_conversation_id uuid := p_conversation_id;
  v_title text := left(regexp_replace(coalesce(trim(p_title), ''), '\s+', ' ', 'g'), 80);
begin
  if p_user_id is null or char_length(trim(coalesce(p_user_content, ''))) = 0
    or char_length(trim(coalesce(p_assistant_content, ''))) = 0 then
    raise exception 'ai_conversation_turn_invalid' using errcode = '22023';
  end if;

  if v_conversation_id is null then
    if v_title = '' then v_title := left(trim(p_user_content), 80); end if;
    v_conversation_id := public.create_ai_conversation(p_user_id, v_title);
  end if;

  if not exists (
    select 1 from public.ai_conversations
    where id = v_conversation_id and user_id = p_user_id
  ) then
    raise exception 'ai_conversation_not_owned' using errcode = '42501';
  end if;

  insert into public.ai_conversation_messages (conversation_id, role, content, metadata)
  values
    (v_conversation_id, 'user', left(trim(p_user_content), 12000), '{}'::jsonb),
    (v_conversation_id, 'assistant', left(trim(p_assistant_content), 12000), coalesce(p_metadata, '{}'::jsonb));

  update public.ai_conversations
  set state = coalesce(p_state, '{}'::jsonb),
      message_count = (select count(*) from public.ai_conversation_messages where conversation_id = v_conversation_id),
      updated_at = now(),
      last_message_at = now()
  where id = v_conversation_id and user_id = p_user_id;

  -- Mantiene el tamaño de cada conversación acotado sin afectar el límite de
  -- conversaciones guardadas. La UI puede informar esta retención.
  delete from public.ai_conversation_messages
  where conversation_id = v_conversation_id
    and id not in (
      select id from public.ai_conversation_messages
      where conversation_id = v_conversation_id
      order by id desc
      limit 150
    );

  update public.ai_conversations
  set message_count = (select count(*) from public.ai_conversation_messages where conversation_id = v_conversation_id)
  where id = v_conversation_id and user_id = p_user_id;

  return v_conversation_id;
end;
$$;

revoke all on function public.create_ai_conversation(uuid, text) from public, anon, authenticated;
revoke all on function public.append_ai_conversation_turn(uuid, uuid, text, text, jsonb, jsonb, text) from public, anon, authenticated;
grant execute on function public.create_ai_conversation(uuid, text) to service_role;
grant execute on function public.append_ai_conversation_turn(uuid, uuid, text, text, jsonb, jsonb, text) to service_role;

create or replace function public.set_user_ai_chat_settings_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists user_ai_chat_settings_updated_at on public.user_ai_chat_settings;
create trigger user_ai_chat_settings_updated_at
before update on public.user_ai_chat_settings
for each row execute function public.set_user_ai_chat_settings_updated_at();
